dependencies {
  // openflexo dep
  implementation flexoFoundation()
  implementation flexoUtils()
  implementation flexoOntology()
  // external dep
  // Following dependency (xtext) has been replaced with new version of EMF
  //implementation 'org.eclipse.xtext:org.eclipse.xtext.xtext:2.10.0'
  implementation group: 'org.eclipse.emf', name: 'org.eclipse.emf.ecore', version: '2.36.0'
  implementation group: 'org.eclipse.emf', name: 'org.eclipse.emf.ecore.xmi', version: '2.37.0'
  implementation group: 'org.eclipse.uml2', name: 'uml-resources', version: '5.0.1'
  implementation group: 'org.eclipse.uml2', name: 'common', version: '2.0.1'
  implementation group: 'org.eclipse.uml2', name: 'uml', version: '5.0.1'
  runtimeOnly group: 'org.eclipse.uml2', name: 'types', version: '2.0.0'
  runtimeOnly group: 'org.eclipse.uml2.uml', name: 'profile-standard', version: '1.0.0'
  // testing dep
  testImplementation flexoFoundationTest()

  // This resource center must always be present at run-time
  runtimeOnly project(':emf-ta-rc')

  // Test resource center
  testRuntimeOnly project(':emf-ta-test-rc')
}
