URI=http://www.polarsys.org/capella/core/modeller/7.0.0
EXTENSION=capella
PACKAGE=org.polarsys.capella.core.data.capellamodeller.CapellamodellerPackage
RESOURCE_FACTORY=org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl
