SOAMLmeta.ecore.uri=http\://www.example.org/metamodelProject/Metamodel/SOAMLmetaModel
SOAMLmeta.ecore.version=2.0
SOAMLmeta.ecore.name=SoamlMetaModel
SOAMLmeta.ecore.XSD_SCHEMA_URI=http\://www.eclipse.org/emf/2002/Ecore
IS_XML=false